### ISSUE TITLE
Can't make a call from eturnal on iOS

### ISSUE THREAD

**Issue by kikimora12304855** [krille-chan/fluffychat#1685]
### Bug Description

I'm not sure what information might be relevant here, but I've tried to provide all the details that seem important from my perspective.

https://github.com/user-attachments/assets/dcbff103-3bb9-42d1-983f-e37c84d5a2a5

### Steps to Reproduce

go to chat
click on the phone icon

### Expected Behavior

when a user clicks on the phone icon, it should connect to another user. 

### App Version

1.25.0

### Additional Platform Information

IOS

#### MATRIX
**matrix server:** synapse
**matrix server version:** 1.125.0
**config matrix:** 
```yaml
turn_uris:
  - "turns:turn.domen.net5349?transport=tcp"  # TURNS (TCP + TLS)
  - "turn:turn.domen.net:3478?transport=udp"   # TURN (UDP)
  - "turn:turn.domen.net:3478?transport=tcp"   # TURN (TCP)
turn_shared_secret: "secret"
turn_user_lifetime: 86400000
turn_allow_guests: true 
```

#### TURN
**turn server:** eturnal
**turn server version:** 1.12.1
**config turn:** 
```yaml
eturnal:

  listen:
    -
      port: 3479
      transport: udp
    -
      port: 3479
      transport: tcp
      proxy_protocol: true

  ## UDP relay port range (usually, several ports per A/V call are required):
  relay_min_port: 49152     # This is the default.
  relay_max_port: 65535     # This is the default.

  blacklist_peers:
    - recommended
  strict_expiry: false      

  ## Logging configuration:
  log_level: debug          # critical | error | warning | notice | info | debug
  log_rotate_size: 1048576  # 10 MiB (default: unlimited, i.e., no rotation).
  log_rotate_count: 1       # Keep 10 rotated log files.
```

#### NGINX
**revers proxy server:** nginx
**revers proxy server version:** 1.22.1
**config revers proxy:** 
```nginx
# TURN (TCP/UDP)
server {
    listen 3478 udp reuseport;
    listen 3478 ;
    proxy_pass 127.0.0.1:3479;
    proxy_protocol on; 
}

# TURNS (TLS)
server {
    listen 5349 ssl;
    proxy_pass 127.0.0.1:3479;
    proxy_protocol on;
    proxy_ssl on;

    ssl_certificate /home/user/.acme.sh/turn.domen.net_ecc/turn.domen.net.cer;
    ssl_certificate_key /home/user/.acme.sh/turn.domen.net_ecc/turn.domen.net.key;
}
```
