### ISSUE TITLE
ntfy notifications not working on self-hosted ntfy server

### ISSUE THREAD

**Issue by Today20092** [krille-chan/fluffychat#853]
### Bug Description

# ntfy self-hosted notifications do not work on fluffy chat.

I used Unified Push's [troubleshooting guide ](https://unifiedpush.org/users/troubleshooting/), downloaded their [app ](https://f-droid.org/packages/org.unifiedpush.example/)"Up-Example" and I was able to receive notifications with that app using my self-hosted ntfy server.

These are the arguments I have on my ntfy _server.yml_

On my reverse proxy (Nginx Proxy Manager), I have that exact url forwarded to port 80.

note: _"domain' replaced by my actual domain_
```yml
base-url: "http://ntfy.domain.xyz"
cache-file: "/var/cache/ntfy/cache.db"
attachment-cache-dir: "/var/cache/ntfy/attachments"
behind-proxy: true
```

![image](https://github.com/krille-chan/fluffychat/assets/79241611/407657bb-3111-4da0-b0de-5ba0e6b0d723)

### Steps to Reproduce

1. Open ntfy
2. Open fluffy chat
3. test notification with friend

### Expected Behavior

on step 3, the test notifcation should come though and work.

### App Version

1.17.1

### Additional Platform Information

Samsung S22

### Additional Context

In Samsung settings, I have notifications on fluffy chat turned on. When it's on, I receive a notification that I have a message the first time. After the first time, if I leave the app open, the test notifications I recieve say the full information of the messages.
